[package]
name = "arb-leaders"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
prometheus = { workspace = true }
lazy_static = "1"
tracing = { workspace = true }
anyhow = { workspace = true }
arb-mempool = { path = "../arb-mempool" }
hex = { workspace = true }

[dev-dependencies]
toml = { workspace = true }
